const colors = [
  {name: 'White', color: 'white', value: 'white'},
  {name: 'Bisque', color: 'bisque', value: 'bisque'},
  {name: 'Black', color: '#1C1C1C', value: 'black'},
  {name: 'Blue', color: 'blue', value: 'blue'},
  {name: 'Carnation', color: '#F778A1', value: 'carnation'},
  {name: 'Chocolate', color: 'chocolate', value: 'chocolate'},
  {name: 'Dark Blue', color: 'darkblue', value: 'darkblue'},
  {name: 'Dark Gray', color: 'darkgray', value: 'darkgray'},
  {name: 'Dark Magenta', color: 'darkmagenta', value: 'darkmagenta'},
  {name: 'Dark Orange', color: 'darkorange', value: 'darkorange'},
  {name: 'Dark Violet', color: 'darkviolet', value: 'darkviolet'},
  {name: 'Deep Sky Blue', color: 'deepskyblue', value: 'deepskyblue'},
  {name: 'Dodger Blue', color: 'dodgerblue', value: 'dodgerblue'},
  {name: 'Forest Green', color: 'forestgreen', value: 'forestgreen'},
  {name: 'Gold', color: 'gold', value: 'gold'},
  {name: 'Green', color: 'green', value: 'green'},
  {name: 'Green Yellow', color: 'greenyellow', value: 'greenyellow'},
  {name: 'Hot Pink', color: 'hotpink', value: 'hotpink'},
  {name: 'Indian Red', color: 'indianred', value: 'indianred'},
  {name: 'Indigo', color: 'indigo', value: 'indigo'},
  {name: 'Lavender', color: '#A74AC7', value: 'lavender'},
  {name: 'Light Lavender', color: '#CD66FF', value: 'lightlavender'},
  {name: 'Light Gray', color: 'lightgray', value: 'lightgray'},
  {name: 'Light Pink', color: 'lightpink', value: 'lightpink'},
  {name: 'Light Sky Blue', color: 'lightskyblue', value: 'lightskyblue'},
  {name: 'Lime Green', color: 'limegreen', value: 'limegreen'},
  {name: 'Magenta', color: 'magenta', value: 'magenta'},
  {name: 'Maroon', color: 'maroon', value: 'maroon'},
  {name: 'Medium Blue', color: 'mediumblue', value: 'mediumblue'},
  {name: 'Medium Orchid', color: 'mediumorchid', value: 'mediumorchid'},
  {name: 'Medium Turquoise', color: 'mediumturquoise', value: 'mediumturquoise'},
  {name: 'Medium Violet Red', color: 'mediumvioletred', value: 'mediumvioletred'},
  {name: 'Orange', color: 'orange', value: 'orange'},
  {name: 'Orange Red', color: 'orangered', value: 'orangered'},
  {name: 'Orchid', color: 'orchid', value: 'orchid'},
  {name: 'Plum', color: 'plum', value: 'plum'},
  {name: 'Purple', color: 'purple', value: 'purple'},
  {name: 'Red', color: 'red', value: 'red'},
  {name: 'Saddle Brown', color: 'saddlebrown', value: 'saddlebrown'},
  {name: 'Violet', color: 'violet', value: 'violet'},
  {name: 'Yellow', color: 'yellow', value: 'yellow'},
];

export default colors;