const flags = [
  { 'name': 'Progress Pride', 'value': 'ProgressPride', 'defaultIcon': '' },
  { 'name': 'Philadelphia Pride', 'value': 'PhiladelphiaPride', 'defaultIcon': '' },
  { 'name': 'Gilbert Baker Pride', 'value': 'GilbertBakerPride', 'defaultIcon': '' },
  { 'name': 'Gilbert Baker Diversity Pride', 'value': 'GilbertBakerDiversityPride', 'defaultIcon': '' },
  { 'name': 'Pride 1978', 'value': 'Pride1978', 'defaultIcon': '' },
  { 'name': 'Pride', 'value': 'Pride', 'defaultIcon': '' },
  { 'name': 'Agender', 'value': 'Agender', 'defaultIcon': '' },
  { 'name': 'Ally', 'value': 'Ally', 'defaultIcon': 'Ally' },
  { 'name': 'Aromantic', 'value': 'Aromantic', 'defaultIcon': '' },
  { 'name': 'Asexual', 'value': 'Asexual', 'defaultIcon': '' },
  { 'name': 'Bear Pride', 'value': 'BearPride', 'defaultIcon': 'Paw' },
  { 'name': 'Bisexual', 'value': 'Bisexual', 'defaultIcon': '' },
  { 'name': 'Genderfluid', 'value': 'Genderfluid', 'defaultIcon': '' },
  { 'name': 'Genderqueer', 'value': 'Genderqueer', 'defaultIcon': '' },
  { 'name': 'Intersex', 'value': 'Intersex', 'defaultIcon': '' },
  { 'name': 'Leather Pride', 'value': 'LeatherPride', 'defaultIcon': 'Heart' },
  { 'name': 'Lesbian Labrys', 'value': 'LesbianLabrys', 'defaultIcon': 'Labrys' },
  { 'name': 'Lesbian', 'value': 'Lesbian', 'defaultIcon': '' },
  { 'name': 'Lipstick Lesbian', 'value': 'LipstickLesbian', 'defaultIcon': 'Kiss' },
  { 'name': 'Non-binary', 'value': 'Non-binary', 'defaultIcon': '' },
  { 'name': 'Pansexual', 'value': 'Pansexual', 'defaultIcon': '' },
  { 'name': 'Polyamory', 'value': 'Polyamory', 'defaultIcon': 'Pi' },
  { 'name': 'Polysexual', 'value': 'Polysexual', 'defaultIcon': '' },
  { 'name': 'Transgender', 'value': 'Transgender', 'defaultIcon': '' },
];

export default flags;