const flagDefinitions = [
  {
    "name":"Gilbert Baker Pride",
    "rightColors":[
      "hotpink",
      "red",
      "orange",
      "yellow",
      "limegreen",
      "mediumturquoise",
      "indigo",
      "darkmagenta"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Pride 1978",
    "rightColors":[
      "red",
      "orange",
      "yellow",
      "limegreen",
      "mediumturquoise",
      "indigo",
      "darkmagenta"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Pride",
    "rightColors":[
      "red",
      "orange",
      "yellow",
      "green",
      "blue",
      "purple"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Agender",
    "rightColors":[
      "black",
      "lightgray",
      "white",
      "greenyellow",
      "white",
      "lightgray",
      "black"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Aromantic",
    "rightColors":[
      "limegreen",
      "greenyellow",
      "white",
      "lightgray",
      "black"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Asexual",
    "rightColors":[
      "black",
      "lightgray",
      "white",
      "purple"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Bisexual",
    "rightColors":[
      "mediumvioletred",
      "mediumvioletred",
      "mediumorchid",
      "mediumblue",
      "mediumblue"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Genderfluid",
    "rightColors":[
      "carnation",
      "white",
      "darkviolet",
      "black",
      "mediumblue"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Genderqueer",
    "rightColors":[
      "lavender",
      "lavender",
      "white",
      "white",
      "forestgreen",
      "forestgreen"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Intersex",
    "rightColors":[
      "gold"
    ],
    "leftColors":[],
    "iconOutline":"purple",
    "iconName":""
  },
  {
    "name":"Lesbian",
    "rightColors":[
      "orangered",
      "darkorange",
      "white",
      "violet",
      "mediumvioletred"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Lesbian Labrys",
    "rightColors":[
      "mediumorchid",
      "mediumorchid",
      "mediumorchid",
      "mediumorchid",
      "mediumorchid",
      "mediumorchid",
      ""
    ],
    "leftColors":[],
    "iconOutline":"black",
    "iconName":"labrys"
  },
  {
    "name":"Non-binary",
    "rightColors":[
      "yellow",
      "white",
      "purple",
      "black"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Pansexual",
    "rightColors":[
      "hotpink",
      "hotpink",
      "gold",
      "gold",
      "deepskyblue",
      "deepskyblue"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Polysexual",
    "rightColors":[
      "magenta",
      "magenta",
      "limegreen",
      "limegreen",
      "dodgerblue",
      "dodgerblue"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Transgender",
    "rightColors":[
      "lightskyblue",
      "lightpink",
      "white",
      "lightpink",
      "lightskyblue"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Bear Pride",
    "rightColors":[
      "saddlebrown",
      "chocolate",
      "gold",
      "bisque",
      "white",
      "darkgray",
      "black"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":"paw"
  },
  {
    "name":"Leather Pride",
    "rightColors":[
      "black",
      "darkblue",
      "black",
      "darkblue",
      "white",
      "darkblue",
      "black",
      "darkblue",
      "black"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":"heart"
  },
  {
    "name":"Lipstick Lesbian",
    "rightColors":[
      "mediumvioletred",
      "mediumorchid",
      "orchid",
      "white",
      "plum",
      "indianred",
      "maroon"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Lipstick Lesbian Icon",
    "rightColors":[
      "mediumvioletred",
      "mediumorchid",
      "orchid",
      "white",
      "plum",
      "indianred",
      "maroon"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":"kiss"
  },
  {
    "name":"Polyamory",
    "rightColors":[
      "blue",
      "blue",
      "red",
      "red",
      "black",
      "black"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":"pi"
  },
  {
    "name":"Philadelphia Pride",
    "rightColors":[
      "black",
      "saddlebrown",
      "red",
      "orange",
      "yellow",
      "green",
      "blue",
      "purple"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Progress Pride",
    "rightColors":[
      "red",
      "orange",
      "yellow",
      "green",
      "blue",
      "purple"
    ],
    "leftColors":[
      "white",
      "lightpink",
      "lightskyblue",
      "saddlebrown",
      "black"
    ],
    "iconOutline":"",
    "iconName":""
  },
  {
    "name":"Black Lives Matter",
    "rightColors":[
      "red",
      "orange",
      "yellow",
      "green",
      "blue",
      "purple"
    ],
    "leftColors":[],
    "iconOutline":"black",
    "iconName":"blm"
  },
  {
    "name":"Straight Ally",
    "rightColors":[
      "black",
      "white",
      "black",
      "white",
      "black",
      "white"
    ],
    "leftColors":[],
    "iconOutline":"",
    "iconName":"ally"
  }
];

export default flagDefinitions;
